version: '3'

services:
  redis:
    image: redis
  api:
    image: licensedbr/devgrid-openweather
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/opt/app/
    depends_on:
      - redis
  worker:
    image: licensedbr/devgrid-openweather
    command: celery -A src.app.tasks worker --loglevel=INFO
    env_file: .env
    volumes:
      - .:/opt/app/
    depends_on:
      - redis
  test:
    image: licensedbr/devgrid-openweather
    command: pytest src/tests/test_app.py